apiVersion: v1
kind: ReplicationController
metadata:
  name: http-go
spec:
  replicas: 5
  selector:
    app: http-go # must be same to template's label
  template:
    metadata:
      name: http-go
      labels:
        app: http-go
    spec:
      containers:
      - name: http-go
        image: gasbugs/http-go
        ports:
        - containerPort: 8080
