apiVersion: v1
kind: Pod
metadata:
  name: nfs-httpd
spec:
  containers:
  - image: httpd
    name: web
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: nfs-volume
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: nfs-volume
    nfs:
      server: 192.168.0.36
      path: /home/nfs