apiVersion: v1
kind: Pod
metadata:
  name: hostpath-httpd
spec:
  containers:
  - image: httpd
    name: web-server
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html  ## 노드와 데이터 공유
    hostPath:
      path: /home/shyeon/workspace/htdocs
      type: Directory
