apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mlflow
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mlflow
    role: mysql
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mlflow
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
      role: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlflow
        role: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "9921"
        - name: MYSQL_DATABASE
          value: "mlflow"
        - name: MYSQL_USER
          value: "mlflow"
        - name: MYSQL_PASSWORD
          value: "mlflow"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
