apiVersion: v1
kind: Pod
metadata:
  name: secret-envars-test
spec:
  containers:
    - name: main-container
      image: gcr.io/google-samples/node-hello:1.0
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass  # secret 이름
              key: username  # 가져올 데이터의 키
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass  # secret 이름
              key: password  # 가져올 데이터의 키
