apiVersion: v1
kind: Pod
metadata:
  name: sa-test
spec:
  serviceAccountName: sa-test
  containers:
  - name: nx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"